### ISSUE TITLE
Participating in developing internet_monitor

### ISSUE THREAD

**Issue by divyanshumehta** [berkmancenter/internet_monitor#5]
I would really like to contribute to this project but I find the resources not well documented on this repositories, is it the actual repository where the work is taking place for some mirror repository.

If this is the main repository I guess there should be well-maintained documentation. Any suggestion are welcome on how should I start contributing to the project

**Comment by ryanttb** [comment]
HI Divyanshu, we're happy you would like to help. This is the primary public repo but since it is mostly an internal project, we haven't document the get started process publicly yet. We'll try to get something in soon. Thanks!

**Comment by divyanshumehta** [comment]
Thank you excited to get started anytime.

**Comment by buttholewenis** [comment]
you should get a real jobbb....... i know you work that Mcdonalds, dont lie to me! I swear I know your mom jake...... you fucking faggot

**Comment by redfuegolight** [comment]
@SteveJobzniak  as you said i think instagram updated their spam filter. 

I've done some tests since yesterday and i can say that if i perfom a new login in my localhost in my house i get a challenge but after i allow the position i can use the api. 
If i perfom a new login from my server bought some week ago just for tests purpose i got a challenge loop. 
I think that's because instagram notice that with your phone or 1 of your devices is login in X position and after several minutes/seconds the same account try to login in another different position. 

For example if i login with proxy in italy i get endless challenge same with french proxy. I also tried to use fake gps thinking i could let know instagram that i'm currently in the same position of proxy but it doesn't seems to work :C Btw i've also used a proxy in my same country not that far from my current location and also got challenge loop (but that could be because is a free open proxy so it could be corrupted by spammers). 

The only thing that works for me but it's kinda usless is that copy 1 of good session file (old file from the correct login, also the one that i never had challenge response) it doesn't matter if it's setting or cooki one and copy to the new login and it seems to recognize a good login, and stop endless challenge.

**Comment by SteveJobzniak** [comment]
@ryanttb Hey, I am seeing "You’re receiving notifications because you were mentioned." - what is going on here? Did the deleted post say something to me? ;-)

**Comment by ryanttb** [comment]
@SteveJobzniak Hi, the comment I deleted was spam. There was a second comment that mentioned you by @alessio but it had nothing to do with this project (something about Instagram). Possibly posted comment to wrong repo and moved it?

**Comment by alessio** [comment]
By me?

**Comment by SteveJobzniak** [comment]
@ryanttb Ahh, thank you. Seems like someone was confused. I'm the co-developer of an Instagram API library and someone must have been confused about what tab they were typing into. ;-)

**Comment by ryanttb** [comment]
@alessio Yep. At least that's the notification I got. Maybe GitHub messed up. Your comment on this issue (which I can't find anymore) started, "@SteveJobzniak as you said i think instagram updated their spam filter."

**Comment by SteveJobzniak** [comment]
@ryanttb I see. Thanks for the message! Strange that it's totally gone from this ticket. It wouldn't be the first time GitHub has done weird things. A few _weeks_ ago, a user created a ticket on one of my projects. The creation date? May 2016. ;-)

**Comment by peter-hank** [comment]
Closing, it's been a while.
